#!/bin/sh -e

# build
#	Simple ts7680ctl build and install script
#
#	Copyright (c) 2017 Joshua Holder - Custom Controls Unlimited Inc.
#################################################################################
# This file is part of ts7680ctl:
#	A Pin Control library for the TS-7680
#
#    ts7680ctl is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ts7680ctl is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with ts7680ctl.  If not, see <http://www.gnu.org/licenses/>.
#################################################################################

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo ""
    exit 1
  fi
}

sudo=${TS7680CTL_SUDO-sudo}

if [ x$1 = "xclean" ]; then
  cd ts7680ctl
  echo -n "ts7680ctl:   "	; make clean
  exit
fi

if [ x$1 = "xuninstall" ]; then
  cd ts7680ctl
  echo -n "ts7680ctl: " ; $make uninstall
  exit
fi

# Only if you know what you're doing!

if [ x$1 = "xdebian" ]; then
  here=`pwd`
  cd debian-template/ts7680ctl
  rm -rf usr
  cd $here/ts7680ctl
  make install-deb
  cd $here/devLib
  make install-deb INCLUDE='-I. -I../ts7680ctl'
  cd $here/ts7680ctl
  make install-deb INCLUDE='-I../ts7680ctl -I../devLib' LDFLAGS=-L../debian-template/ts7680ctl/usr/lib
  cd $here/debian-template
  fakeroot dpkg-deb --build ts7680ctl
  mv ts7680ctl.deb  ts7680ctl-`cat $here/VERSION`-1.deb
  exit
fi

if [ x$1 != "x" ]; then
  echo "Usage: $0 [clean | uninstall]"
  exit 1
fi

  echo "ts7680ctl Build script"
  echo "====================="
  echo

 # hardware=`fgrep Hardware /proc/cpuinfo | head -1 | awk '{ print $3 }'`

  echo
  echo "ts7680ctl Library"
  cd ts7680ctl
  echo "Made it to the first"
  $make uninstall
  echo "Made it after"
  if [ x$1 = "xstatic" ]; then
    make -j5 static
    check_make_ok
    $make install-static
  else
    make
    check_make_ok
    $make install
  fi
  check_make_ok

#  echo
#  echo "ts7680ctl Devices Library"
#  cd ../devLib
#  $sudo make uninstall
#  if [ x$1 = "xstatic" ]; then
#    make -j5 static
#    check_make_ok
#    $sudo make install-static
#  else
#    make -j5
#    check_make_ok
#    $sudo make install
#  fi
#  check_make_ok

#  echo
#  echo "ts7680ctl Utility"
#  cd ../ts7680ctl
#  make -j5
#  check_make_ok
#  $sudo make install
#  check_make_ok

echo ""
echo "All Done."
echo ""
echo ""
